---
kind: pipeline
name: default

trigger:
  branch:
    - master

steps:
  - name: Restore cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules

  - name: Install packages
    image: node:16.14.2
    commands:
      - yarn config set cache-folder .yarn-cache
      - yarn install --pure-lockfile

  - name: Build
    image: node:16.14.2
    commands:
      - ./node_modules/.bin/ng build --configuration production --output-path /drone/src/build

  - name: Deploy
    image: robvankeilegom/ssh-rsync
    environment:
      SSH_KEY:
        from_secret: drone_ssh_key
      SSH_USER:
        from_secret: drone_ssh_user
      SSH_PORT:
        from_secret: drone_ssh_port
    commands:
      - eval `ssh-agent -s`
      - echo "$SSH_KEY" | ssh-add -
      - mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
      - ssh-keyscan -p $SSH_PORT robvankeilegom.be >> ~/.ssh/known_hosts
      - mkdir -p ~/.ssh
      - rsync -av -e "ssh -p $SSH_PORT" /drone/src/build/ $SSH_USER@robvankeilegom.be:~/websites/bes.robvankeilegom.be/current --delete

